2022-07-12 14:16:37,868 - pyswarms.single.global_best - INFO - Optimize for [0.         2.30258509] iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2022-07-12 14:20:20,414 - pyswarms.single.general_optimizer - INFO - Optimize for [0.         2.30258509] iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2022-07-12 14:23:11,303 - pyswarms.single.general_optimizer - INFO - Optimize for 2 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2022-07-12 14:26:44,146 - pyswarms.single.general_optimizer - INFO - Optimize for 2 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2022-07-12 14:29:09,922 - pyswarms.backend.generators - ERROR - Bounds and/or init_pos should be of size (2,)
Traceback (most recent call last):
  File "c:\Users\tzehl\AppData\Local\Programs\Python\Python39\lib\site-packages\pyswarms\backend\generators.py", line 67, in generate_swarm
    raise ValueError("User-defined init_pos is out of bounds.")
ValueError: User-defined init_pos is out of bounds.
2022-07-12 14:41:17,123 - pyswarms.backend.generators - ERROR - generate_swarm() takes an int for n_particles and dimensions and an array for bounds
Traceback (most recent call last):
  File "c:\Users\tzehl\AppData\Local\Programs\Python\Python39\lib\site-packages\pyswarms\backend\generators.py", line 81, in generate_swarm
    pos = center * np.random.uniform(
  File "mtrand.pyx", line 1134, in numpy.random.mtrand.RandomState.uniform
  File "_common.pyx", line 579, in numpy.random._common.cont
  File "_common.pyx", line 487, in numpy.random._common.cont_broadcast_2
TypeError: 'function' object cannot be interpreted as an integer
2022-07-12 14:42:44,344 - pyswarms.single.global_best - INFO - Optimize for 1 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2022-07-12 14:43:32,058 - pyswarms.single.global_best - INFO - Optimize for 1 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2022-07-12 14:44:30,784 - pyswarms.single.global_best - INFO - Optimize for 1 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2022-07-12 14:45:06,852 - pyswarms.single.global_best - INFO - Optimize for 1 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2022-07-12 14:46:03,853 - pyswarms.single.global_best - INFO - Optimize for 1 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2022-07-12 14:46:18,491 - pyswarms.backend.generators - ERROR - Bounds and/or init_pos should be of size (4900,)
Traceback (most recent call last):
  File "c:\Users\tzehl\AppData\Local\Programs\Python\Python39\lib\site-packages\pyswarms\backend\generators.py", line 81, in generate_swarm
    pos = center * np.random.uniform(
  File "mtrand.pyx", line 1134, in numpy.random.mtrand.RandomState.uniform
  File "_common.pyx", line 579, in numpy.random._common.cont
  File "_common.pyx", line 496, in numpy.random._common.cont_broadcast_2
  File "__init__.pxd", line 742, in numpy.PyArray_MultiIterNew3
ValueError: shape mismatch: objects cannot be broadcast to a single shape.  Mismatch is between arg 0 with shape (2, 4900) and arg 1 with shape (2, 2).
2022-07-12 14:46:25,663 - pyswarms.backend.generators - ERROR - Bounds and/or init_pos should be of size (70,)
Traceback (most recent call last):
  File "c:\Users\tzehl\AppData\Local\Programs\Python\Python39\lib\site-packages\pyswarms\backend\generators.py", line 81, in generate_swarm
    pos = center * np.random.uniform(
  File "mtrand.pyx", line 1134, in numpy.random.mtrand.RandomState.uniform
  File "_common.pyx", line 579, in numpy.random._common.cont
  File "_common.pyx", line 496, in numpy.random._common.cont_broadcast_2
  File "__init__.pxd", line 742, in numpy.PyArray_MultiIterNew3
ValueError: shape mismatch: objects cannot be broadcast to a single shape.  Mismatch is between arg 0 with shape (2, 70) and arg 1 with shape (2, 2).
2022-07-12 14:46:33,250 - pyswarms.single.global_best - INFO - Optimize for 1 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2022-07-12 14:46:46,227 - pyswarms.single.global_best - INFO - Optimize for 1 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2022-07-12 14:47:08,350 - pyswarms.single.global_best - INFO - Optimize for 1 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2022-07-12 14:47:11,586 - pyswarms.single.global_best - INFO - Optimize for 1 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2022-07-12 14:47:55,522 - pyswarms.single.global_best - INFO - Optimize for 10 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2022-07-12 14:48:52,665 - pyswarms.single.global_best - INFO - Optimize for 10 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2022-07-12 14:48:58,250 - pyswarms.single.global_best - INFO - Optimize for 10 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2022-07-12 14:51:06,226 - pyswarms.single.global_best - INFO - Optimize for 10 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2022-07-12 14:51:10,742 - pyswarms.single.global_best - INFO - Optimize for 10 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2022-07-12 14:51:34,961 - pyswarms.backend.generators - ERROR - Bounds and/or init_pos should be of size (4900,)
Traceback (most recent call last):
  File "c:\Users\tzehl\AppData\Local\Programs\Python\Python39\lib\site-packages\pyswarms\backend\generators.py", line 81, in generate_swarm
    pos = center * np.random.uniform(
  File "mtrand.pyx", line 1134, in numpy.random.mtrand.RandomState.uniform
  File "_common.pyx", line 579, in numpy.random._common.cont
  File "_common.pyx", line 496, in numpy.random._common.cont_broadcast_2
  File "__init__.pxd", line 742, in numpy.PyArray_MultiIterNew3
ValueError: shape mismatch: objects cannot be broadcast to a single shape.  Mismatch is between arg 0 with shape (2, 4900) and arg 1 with shape (2, 2).
2022-07-12 14:52:50,233 - pyswarms.single.global_best - INFO - Optimize for 10 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2022-07-12 14:54:34,331 - pyswarms.backend.generators - ERROR - generate_swarm() takes an int for n_particles and dimensions and an array for bounds
Traceback (most recent call last):
  File "c:\Users\tzehl\AppData\Local\Programs\Python\Python39\lib\site-packages\pyswarms\backend\generators.py", line 81, in generate_swarm
    pos = center * np.random.uniform(
  File "mtrand.pyx", line 1134, in numpy.random.mtrand.RandomState.uniform
  File "_common.pyx", line 579, in numpy.random._common.cont
  File "_common.pyx", line 487, in numpy.random._common.cont_broadcast_2
TypeError: 'tuple' object cannot be interpreted as an integer
2022-07-12 14:54:54,115 - pyswarms.single.global_best - INFO - Optimize for 10 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2022-07-12 15:08:44,685 - pyswarms.single.global_best - INFO - Optimize for 10 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2022-07-12 15:10:37,194 - pyswarms.single.global_best - INFO - Optimize for 10 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2022-07-12 15:12:31,800 - pyswarms.single.global_best - INFO - Optimize for 10 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2022-07-12 15:14:32,886 - pyswarms.single.global_best - INFO - Optimize for 10 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2022-07-12 15:16:54,889 - pyswarms.single.global_best - INFO - Optimize for 100 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2022-07-12 15:17:10,141 - pyswarms.single.global_best - INFO - Optimize for 100 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2022-07-12 15:17:57,018 - pyswarms.single.global_best - INFO - Optimize for 100 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2022-07-12 15:18:17,230 - pyswarms.single.global_best - INFO - Optimize for 100 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2022-07-12 15:18:27,344 - pyswarms.single.global_best - INFO - Optimize for 100 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2022-07-12 15:19:08,335 - pyswarms.single.global_best - INFO - Optimize for 100 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2022-07-12 15:20:29,819 - pyswarms.single.global_best - INFO - Optimize for 100 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2022-07-12 15:22:16,666 - pyswarms.backend.generators - ERROR - Bounds and/or init_pos should be of size (4900,)
Traceback (most recent call last):
  File "c:\Users\tzehl\AppData\Local\Programs\Python\Python39\lib\site-packages\pyswarms\backend\generators.py", line 81, in generate_swarm
    pos = center * np.random.uniform(
  File "mtrand.pyx", line 1134, in numpy.random.mtrand.RandomState.uniform
  File "_common.pyx", line 579, in numpy.random._common.cont
  File "_common.pyx", line 496, in numpy.random._common.cont_broadcast_2
  File "__init__.pxd", line 742, in numpy.PyArray_MultiIterNew3
ValueError: shape mismatch: objects cannot be broadcast to a single shape.  Mismatch is between arg 0 with shape (2, 4900) and arg 1 with shape (2, 2).
2022-07-12 15:22:25,545 - pyswarms.backend.generators - ERROR - Bounds and/or init_pos should be of size (70,)
Traceback (most recent call last):
  File "c:\Users\tzehl\AppData\Local\Programs\Python\Python39\lib\site-packages\pyswarms\backend\generators.py", line 81, in generate_swarm
    pos = center * np.random.uniform(
  File "mtrand.pyx", line 1134, in numpy.random.mtrand.RandomState.uniform
  File "_common.pyx", line 579, in numpy.random._common.cont
  File "_common.pyx", line 496, in numpy.random._common.cont_broadcast_2
  File "__init__.pxd", line 742, in numpy.PyArray_MultiIterNew3
ValueError: shape mismatch: objects cannot be broadcast to a single shape.  Mismatch is between arg 0 with shape (2, 70) and arg 1 with shape (2, 2).
2022-07-12 15:22:32,448 - pyswarms.single.global_best - INFO - Optimize for 100 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2022-07-12 15:22:47,165 - pyswarms.single.global_best - INFO - Optimize for 100 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2022-07-12 15:24:29,953 - pyswarms.single.global_best - INFO - Optimize for 1 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2022-07-12 15:25:23,839 - pyswarms.single.global_best - INFO - Optimize for 1 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2022-07-12 15:32:53,400 - pyswarms.single.global_best - INFO - Optimize for 1 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2022-07-12 15:33:23,659 - pyswarms.single.global_best - INFO - Optimize for 1 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2022-07-12 15:34:00,722 - pyswarms.single.global_best - INFO - Optimize for 1 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2022-07-12 15:34:19,519 - pyswarms.single.global_best - INFO - Optimize for 1 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2022-07-12 15:35:15,032 - pyswarms.single.global_best - INFO - Optimize for 1 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2022-07-12 15:37:02,671 - pyswarms.single.global_best - INFO - Optimize for 1 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2022-07-12 15:37:24,661 - pyswarms.single.global_best - INFO - Optimize for 1 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2022-07-12 15:37:52,777 - pyswarms.single.global_best - INFO - Optimize for 1 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2022-07-12 15:40:55,721 - pyswarms.backend.generators - ERROR - Bounds and/or init_pos should be of size (1,)
Traceback (most recent call last):
  File "c:\Users\tzehl\AppData\Local\Programs\Python\Python39\lib\site-packages\pyswarms\backend\generators.py", line 81, in generate_swarm
    pos = center * np.random.uniform(
  File "mtrand.pyx", line 1134, in numpy.random.mtrand.RandomState.uniform
  File "_common.pyx", line 579, in numpy.random._common.cont
  File "_common.pyx", line 497, in numpy.random._common.cont_broadcast_2
  File "_common.pyx", line 230, in numpy.random._common.validate_output_shape
ValueError: Output size (10, 1) is not compatible with broadcast dimensions of inputs (10, 2).
2022-07-12 15:41:04,121 - pyswarms.single.global_best - INFO - Optimize for 1 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2022-07-12 15:41:11,458 - pyswarms.single.global_best - INFO - Optimize for 1 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2022-07-12 15:41:18,452 - pyswarms.single.global_best - INFO - Optimize for 1 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2022-07-12 15:41:33,419 - pyswarms.single.global_best - INFO - Optimize for 1 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2022-07-12 15:41:50,124 - pyswarms.single.global_best - INFO - Optimize for 1 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2022-07-12 15:42:01,347 - pyswarms.single.global_best - INFO - Optimize for 1 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2022-07-12 15:42:06,809 - pyswarms.single.global_best - INFO - Optimize for 1 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2022-07-12 15:42:13,232 - pyswarms.single.global_best - INFO - Optimize for 1 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2022-07-12 15:45:01,145 - pyswarms.single.global_best - INFO - Optimize for 19 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2022-07-12 15:45:08,994 - pyswarms.single.global_best - INFO - Optimize for 10 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2022-07-12 15:45:14,035 - pyswarms.single.global_best - INFO - Optimize for 10 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2022-07-12 15:45:20,557 - pyswarms.single.global_best - INFO - Optimize for 10 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2022-07-12 15:45:39,217 - pyswarms.single.global_best - INFO - Optimize for 10 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2022-07-12 15:47:15,317 - pyswarms.single.global_best - INFO - Optimize for 10 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2022-07-14 15:07:08,534 - root - CRITICAL - This will get logged
2022-07-18 09:24:06,583 - pyswarms.backend.generators - ERROR - generate_swarm() takes an int for n_particles and dimensions and an array for bounds
Traceback (most recent call last):
  File "c:\Users\I538840\Anaconda3\lib\site-packages\pyswarms\backend\generators.py", line 70, in generate_swarm
    pos = center * np.random.uniform(
  File "mtrand.pyx", line 1112, in numpy.random.mtrand.RandomState.uniform
  File "_common.pyx", line 577, in numpy.random._common.cont
TypeError: 'numpy.float64' object cannot be interpreted as an integer
2022-07-18 09:32:48,972 - numexpr.utils - INFO - Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
2022-07-18 09:32:48,975 - numexpr.utils - INFO - NumExpr defaulting to 8 threads.
2022-07-18 09:36:53,696 - pyswarms.backend.generators - ERROR - generate_swarm() takes an int for n_particles and dimensions and an array for bounds
Traceback (most recent call last):
  File "c:\Users\I538840\Anaconda3\lib\site-packages\pyswarms\backend\generators.py", line 70, in generate_swarm
    pos = center * np.random.uniform(
  File "mtrand.pyx", line 1112, in numpy.random.mtrand.RandomState.uniform
  File "_common.pyx", line 577, in numpy.random._common.cont
TypeError: 'numpy.float64' object cannot be interpreted as an integer
2022-07-18 09:44:14,005 - pyswarms.backend.generators - ERROR - generate_swarm() takes an int for n_particles and dimensions and an array for bounds
Traceback (most recent call last):
  File "c:\Users\I538840\Anaconda3\lib\site-packages\pyswarms\backend\generators.py", line 70, in generate_swarm
    pos = center * np.random.uniform(
  File "mtrand.pyx", line 1112, in numpy.random.mtrand.RandomState.uniform
  File "_common.pyx", line 577, in numpy.random._common.cont
TypeError: 'numpy.float64' object cannot be interpreted as an integer
2022-07-18 09:46:18,143 - numexpr.utils - INFO - Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
2022-07-18 09:46:18,148 - numexpr.utils - INFO - NumExpr defaulting to 8 threads.
2022-07-18 10:45:56,507 - pyswarms.backend.generators - ERROR - generate_swarm() takes an int for n_particles and dimensions and an array for bounds
Traceback (most recent call last):
  File "c:\Users\I538840\Anaconda3\lib\site-packages\pyswarms\backend\generators.py", line 70, in generate_swarm
    pos = center * np.random.uniform(
  File "mtrand.pyx", line 1112, in numpy.random.mtrand.RandomState.uniform
  File "_common.pyx", line 577, in numpy.random._common.cont
TypeError: 'numpy.float64' object cannot be interpreted as an integer
2022-07-18 10:46:51,188 - numexpr.utils - INFO - Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
2022-07-18 10:46:51,196 - numexpr.utils - INFO - NumExpr defaulting to 8 threads.
2022-07-18 14:50:47,858 - pyswarms.backend.generators - ERROR - generate_swarm() takes an int for n_particles and dimensions and an array for bounds
Traceback (most recent call last):
  File "C:\Users\ti-he\AppData\Roaming\Python\Python37\site-packages\pyswarms\backend\generators.py", line 71, in generate_swarm
    low=0.0, high=1.0, size=(n_particles, dimensions)
  File "mtrand.pyx", line 1118, in numpy.random.mtrand.RandomState.uniform
  File "_common.pyx", line 598, in numpy.random._common.cont
TypeError: 'numpy.float64' object cannot be interpreted as an integer
2022-07-21 18:08:15,849 - pyswarms.single.global_best - INFO - Optimize for [0.] iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9, 'k': 2, 'p': 2}
2022-07-21 18:16:14,266 - pyswarms.single.global_best - INFO - Optimize for [0.] iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9, 'k': 2, 'p': 2}
